//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSVdisp {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MSVdisp.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LED {
            get {
                object obj = ResourceManager.GetObject("LED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LED_zhas {
            get {
                object obj = ResourceManager.GetObject("LED_zhas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný &lt;cNamedTextureSetBlueprint-sTextureEntry&gt;
        ///								&lt;Element&gt;
        ///									&lt;Value&gt;
        ///										&lt;Attribute name=&quot;TextureName&quot;&gt;
        ///											&lt;cDeltaString&gt;
        ///												&lt;Element&gt;
        ///													&lt;Value&gt;{0}&lt;/Value&gt;
        ///												&lt;/Element&gt;
        ///											&lt;/cDeltaString&gt;
        ///										&lt;/Attribute&gt;
        ///										&lt;Attribute name=&quot;TextureID&quot;&gt;
        ///											&lt;cDeltaString&gt;
        ///												&lt;Element&gt;
        ///													&lt;Value&gt;{1}&lt;/Value&gt;
        ///												&lt;/Element&gt;
        ///											&lt;/cDeltaString&gt;
        ///										&lt;/Attribute&gt;
        ///									&lt;/Value&gt;
        ///								&lt;/Ele [zbytek řetězce byl zkrácen];.
        /// </summary>
        internal static string xmlData {
            get {
                return ResourceManager.GetString("xmlData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný &lt;/Value&gt;
        ///					&lt;/Element&gt;
        ///				&lt;/__Indexed__cNamedTextureSetBlueprint-sTextureEntry&gt;
        ///			&lt;/Attribute&gt;
        ///		&lt;/Value&gt;
        ///	&lt;/Element&gt;
        ///&lt;/cNamedTextureSetBlueprint&gt;.
        /// </summary>
        internal static string xmlEnd {
            get {
                return ResourceManager.GetString("xmlEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;cNamedTextureSetBlueprint&gt;
        ///	&lt;Element&gt;
        ///		&lt;Value&gt;
        ///			&lt;Attribute name=&quot;Name&quot;&gt;
        ///				&lt;cDeltaString&gt;
        ///					&lt;Element&gt;
        ///						&lt;Value&gt;MSV ex 5x10&lt;/Value&gt;
        ///					&lt;/Element&gt;
        ///				&lt;/cDeltaString&gt;
        ///			&lt;/Attribute&gt;
        ///			&lt;Attribute name=&quot;TextureEntry&quot;&gt;
        ///				&lt;__Indexed__cNamedTextureSetBlueprint-sTextureEntry&gt;
        ///					&lt;Element&gt;
        ///						&lt;Value&gt;.
        /// </summary>
        internal static string xmlStart {
            get {
                return ResourceManager.GetString("xmlStart", resourceCulture);
            }
        }
    }
}
